#!/usr/bin/env bash
# In case repo name is changed, run this script
# to change the repo name in the files

# ANSI color codes for output messages
GREEN='\033[0;32m'  # Green for success
RED='\033[0;31m'    # Red for error
YELLOW='\033[1;33m' # Yellow for warnings
NC='\033[0m'        # No color

# Function to print colored messages
print_message() {
    local msg="$1"
    local color="$2"
    echo -e "${color}${msg}${NC}"
}

# Check if the correct number of arguments are provided
if [ "$#" -lt 2 ]; then
    print_message "Usage: $0 old_repo_name new_repo_name" "$RED"
    exit 1
fi

# Extract the old domain and new domain from the arguments
old_repo_name="$1"
new_repo_name="$2"

./replace_any_ip_or_domain * ../sql_related/* /set_app /unset_app $old_repo_name $new_repo_name
./config_ngx_create_symlink

# Success message
print_message "Name substitution completed!" "$GREEN"
